INFO:2024-07-31 15:26:16,810:MainThread:Dhan.py  started system
INFO:2024-07-31 15:26:16,810:MainThread:STARTED THE PROGRAM
INFO:2024-07-31 16:54:43,022:MainThread:Dhan.py  started system
INFO:2024-07-31 16:54:43,022:MainThread:STARTED THE PROGRAM
INFO:2024-07-31 17:21:58,922:MainThread:Dhan.py  started system
INFO:2024-07-31 17:21:58,923:MainThread:STARTED THE PROGRAM
INFO:2024-07-31 18:26:00,053:MainThread:Dhan.py  started system
INFO:2024-07-31 18:26:00,053:MainThread:STARTED THE PROGRAM
ERROR:2024-07-31 18:26:06,351:MainThread:problem close all trades
Traceback (most recent call last):
  File "C:\Users\SATHISH\AppData\Local\Programs\Python\Python38\lib\cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'Pdb' object has no attribute 'do_tsl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\tradehull\Dhan codebase\Dhan_Tradehull.py", line 831, in cancel_all_orders
    product_detail = {'MIS': self.xts1.PRODUCT_MIS, 'NRML': self.xts1.PRODUCT_NRML, 'CNC': 'CNC'}
AttributeError: 'Tradehull' object has no attribute 'xts1'
INFO:2024-07-31 18:26:47,753:MainThread:Dhan.py  started system
INFO:2024-07-31 18:26:47,753:MainThread:STARTED THE PROGRAM
ERROR:2024-07-31 18:26:56,777:MainThread:problem close all trades
Traceback (most recent call last):
  File "C:\Users\SATHISH\AppData\Local\Programs\Python\Python38\lib\cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'Pdb' object has no attribute 'do_tsl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\tradehull\Dhan codebase\Dhan_Tradehull.py", line 826, in cancel_all_orders
    product_detail = {'MIS': self.xts1.PRODUCT_MIS, 'NRML': self.xts1.PRODUCT_NRML, 'CNC': 'CNC'}
AttributeError: 'Tradehull' object has no attribute 'xts1'
INFO:2024-07-31 18:28:02,186:MainThread:Dhan.py  started system
INFO:2024-07-31 18:28:02,186:MainThread:STARTED THE PROGRAM
ERROR:2024-07-31 18:28:09,620:MainThread:problem close all trades
Traceback (most recent call last):
  File "C:\Users\SATHISH\AppData\Local\Programs\Python\Python38\lib\cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'Pdb' object has no attribute 'do_tsl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\tradehull\Dhan codebase\Dhan_Tradehull.py", line 826, in cancel_all_orders
    product_detail = {'MIS': self.xts1.PRODUCT_MIS, 'NRML': self.xts1.PRODUCT_NRML, 'CNC': 'CNC'}
AttributeError: 'Tradehull' object has no attribute 'xts1'
INFO:2024-07-31 18:29:52,894:MainThread:Dhan.py  started system
INFO:2024-07-31 18:29:52,894:MainThread:STARTED THE PROGRAM
